[tox]
# downgrade virtualenv to 20.21.0 have python 3.6 and earlier support
# https://github.com/tox-dev/tox/issues/2989
requires = virtualenv<20.22.0
envlist =
    py36
    py37
    py38
    py39
    py310
    py311

[testenv]
deps =
    -r tests/requirements.txt
commands =
    coverage erase
    coverage run -m pytest -W error -v {posargs} \
        tests/unit
    coverage report
