[tox]
# downgrade virtualenv to 20.21.0 have python 3.6 and earlier support
# https://github.com/tox-dev/tox/issues/2989
requires = virtualenv<20.22.0
envlist =
    py34
    py35
    py36

[testenv]
passenv =
    NEO4J_USER
    NEO4J_PASSWORD
    NEO4J_URI
commands =
    python setup.py develop
    pip install --upgrade -r {toxinidir}/tests/requirements.txt
    coverage erase
    coverage run -m pytest -v {posargs} tests/performance
    coverage report
