[tox]
envlist =
    py{310,311,312,313,314}-{performance}-{allextra}
    py{311,312,313}-{unit,integration}-{noextra,allextra}
    py{310,314}-{unit,integration}-{noextra,numpy,pandas,pyarrow,http,allextra}

[testenv]
passenv = TEST_*, GITHUB_ACTIONS
dependency_groups =
    test
extras =
    numpy,allextra: numpy
    pandas,allextra: pandas
    pyarrow,allextra: pyarrow
    http,allextra: http
setenv =
    COVERAGE_FILE={envdir}/.coverage
    TEST_SUITE_NAME={envname}
usedevelop = true
warnargs =
    -W error -W ignore::pytest.PytestUnraisableExceptionWarning
parallel_show_output = true
commands =
    coverage erase
    unit: coverage run -m pytest {[testenv]warnargs} {posargs} tests/unit
    integration: coverage run -m pytest {[testenv]warnargs} {posargs} tests/integration
    performance: python -m pytest --benchmark-autosave {posargs} tests/performance
    unit,integration: coverage report
