[tox]
envlist =
    cov_clean
    cov_report
    {a,b,c}-py315-prepare
    py{310,311,312,313,314,315}-{performance}-{allextras}
    py{311,312,313,314}-{unit-sync,unit-async,unit-mixed,integration}-{noextras,allextras}
    py{310,315}-{unit-sync,unit-async,unit-mixed,integration}-{noextras,numpy,pandas,pyarrow,http,allextras}

[testenv]
passenv =
    TEST_*
    GITHUB_ACTIONS
    # [bump-pyarrow] search tag when bumping pyarrow
    # (env pass-through only needed when building wheel locally)
    PYARROW_WITH_*
dependency_groups =
    test
extras =
    numpy,allextras: numpy
    pandas,allextras: pandas
    pyarrow,allextras: pyarrow
    http,allextras: http
setenv =
    TEST_SUITE_NAME={envname}
usedevelop = true
warnargs =
    unit,integration: -W error -W ignore::pytest.PytestUnraisableExceptionWarning
unitargs=
    unit-sync: tests/unit/sync
    unit-async: tests/unit/async_
    unit-mixed: --ignore tests/unit/sync --ignore tests/unit/async_ tests/unit
covargs=
    unit,integration: --cov=src/neo4j --cov-append
parallel_show_output = true
commands =
    prepare: python -m pip cache dir
    prepare: python -m pip cache info
    prepare: python -m pip cache list pyarrow
    unit: python -m pytest {[testenv]covargs} --benchmark-disable {[testenv]warnargs} {posargs} {[testenv]unitargs}
    integration: python -m pytest {[testenv]covargs} --benchmark-disable {[testenv]warnargs} {posargs} tests/integration
    performance: python -m pytest --benchmark-autosave {posargs} tests/performance
depends =
    unit,integration: cov_clean
    py315-{pyarrow,http,allextras}: *-py315-prepare

# [bump-pyarrow] search tag when bumping pyarrow
# install pyarrow to build wheel and populate pip cache
# this avoids concurrent builds which helps to
#  * avoid concurrency issues in the build backend
#  * overloading the system with building the same native extension multiple
#    times (possibly in parallel)
[testenv:{a,b,c}-py315-prepare]
extras =
    b: pyarrow
    b: http
depends =
    b: a-py315-prepare
    c: b-py315-prepare

[testenv:cov_clean]
dependency_groups =
    test
skip_install = true
commands = coverage erase

[testenv:cov_report]
dependency_groups =
    test
skip_install = true
commands = coverage report --skip-empty --show-missing
depends =
    *-unit-*
    *-integration-*
