[tox]
envlist =
    py{310,311,312,313,314}-{unit,integration,performance}-extras
    py{310,314}-{unit,integration,performance}-noextras

[testenv]
passenv = TEST_*
dependency_groups =
    test
extras =
    extras: numpy
    extras: pandas
    extras: pyarrow
setenv =
    COVERAGE_FILE={envdir}/.coverage
    TEST_SUITE_NAME={envname}
usedevelop = true
warnargs =
    -W error -W ignore::pytest.PytestUnraisableExceptionWarning
parallel_show_output = true
commands =
    coverage erase
    unit: coverage run -m pytest {[testenv]warnargs} -v {posargs} tests/unit
    integration: coverage run -m pytest {[testenv]warnargs} -v {posargs} tests/integration
    performance: python -m pytest --benchmark-autosave -v {posargs} tests/performance
    unit,integration: coverage report
