!: BOLT 3
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9001

C: HELLO {"user_agent": "test", "scheme": "basic", "principal": "test", "credentials": "test"}
S: SUCCESS {"server": "Neo4j/3.0.0", "connection_id": "123e4567-e89b-12d3-a456-426655440000"}
C: BEGIN {"mode": "r", "tx_metadata": {"foo": "bar"}, "tx_timeout": 3000}
S: SUCCESS {}
C: RUN "UNWIND [1,2,3,4] AS x RETURN x" {} {}
S: SUCCESS {"fields": ["x"], "t_first": 300}
C: PULL_ALL
S: RECORD [1]
   RECORD [2]
   RECORD [3]
   RECORD [4]
   SUCCESS {"type": "r", "t_last": 500}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark-test-1"}
