!: BOLT 3
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9001

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": {"address": "localhost:9001"}} {"mode": "r"}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [300, [{"role":"ROUTE","addresses":["127.0.0.1:9001","127.0.0.1:9002","127.0.0.1:9003"]},{"role":"READ","addresses":["127.0.0.1:9004","127.0.0.1:9005"]},{"role":"WRITE","addresses":[]}]]
   SUCCESS {}
