!: AUTO INIT
!: AUTO RESET

C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx1", "bookmarks": ["neo4j:bookmark:v1:tx0", "neo4j:bookmark:v1:tx1"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx2", "bookmarks": ["neo4j:bookmark:v1:tx2"]}
   SUCCESS {}

C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx2", "bookmarks": ["neo4j:bookmark:v1:tx2"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx3", "bookmarks": ["neo4j:bookmark:v1:tx3"]}
   SUCCESS {}
