!: AUTO INIT
!: AUTO RESET

C: RUN "BEGIN" {}
   DISCARD_ALL
S: SUCCESS {"fields": []}
   SUCCESS {}

C: RUN "RETURN $x" {"x": 1}
   PULL_ALL
S: SUCCESS {"fields": ["x"]}
   RECORD [1]
   SUCCESS {}

C: RUN "" {"x": 1}
   PULL_ALL
S: SUCCESS {"fields": ["x"]}
   RECORD [1]
   SUCCESS {}

C: RUN "COMMIT" {}
   DISCARD_ALL
S: SUCCESS {"bookmark": "bookmark:1", "bookmarks": ["bookmark:1"]}
   SUCCESS {}
