!: AUTO INIT
!: AUTO RESET

C: RUN "BEGIN" {}
   PULL_ALL
S: SUCCESS {"fields": []}
   SUCCESS {}

C: RUN "RETURN 1" {}
   PULL_ALL
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}

C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx1", "bookmarks": ["neo4j:bookmark:v1:tx1"]}
   SUCCESS {}

C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx1", "bookmarks": ["neo4j:bookmark:v1:tx1"]}
   PULL_ALL
S: SUCCESS {"fields": []}
   SUCCESS {}

C: RUN "RETURN 1" {}
   PULL_ALL
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}

C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx2", "bookmarks": ["neo4j:bookmark:v1:tx2"]}
   SUCCESS {}
