!: AUTO INIT
!: AUTO RESET

C: RUN "BEGIN" {}
   PULL_ALL
S: SUCCESS {"fields": []}
   SUCCESS {}

C: RUN "RETURN $x" {"x": 1}
   PULL_ALL
S: SUCCESS {"fields": ["x"]}
   RECORD [1]
   SUCCESS {}

C: RUN "RETURN $x" {"x": 1}
   PULL_ALL
S: SUCCESS {"fields": ["x"]}
   RECORD [1]
   SUCCESS {}

C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx1", "bookmarks": ["neo4j:bookmark:v1:tx1"]}
   SUCCESS {}
