!: BOLT 4
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"user_agent": "test", "scheme": "basic", "principal": "test", "credentials": "test"}
S: SUCCESS {server”: "Neo4j/4.0.0", "connection_id": "123e4567-e89b-12d3-a456-426655440000"}
C: RUN "MATCH (n:Node) RETURN n.name as name" {} {}
S: SUCCESS {"fields": ["name"], "t_first": 1234}
C: PULL {"n": -1}
S: RECORD ["A"]
   RECORD ["B"]
   RECORD ["C"]
   SUCCESS {"bookmark": "bookmark:1:autocommit", "t_last": "12345", "type": "r", "stats": {}, "plan": {"operatorType": "undefined"}, "profile": {}, "notifications": {}, "db": "system"}