!: BOLT 4.1
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9002

C: HELLO {"scheme": "basic", "principal": "test", "credentials": "test", "user_agent": "test", "routing": {"address": "localhost:9001", "policy": "my_policy", "region": "china"}}
S: SUCCESS {"server": "Neo4j/4.1.0", "connection_id": "bolt-123456789"}
C: RUN "RETURN 1 AS x" {} {"mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"fields": ["x"]}
   RECORD [1]
   SUCCESS {"bookmark": "neo4j:bookmark-test-2", "type": "r", "t_last": 5, "db": "system"}
