!: BOLT 4
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9004

C: RUN "RETURN 1" {} {"mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}

C: RUN "RETURN 1" {} {"mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}

C: RUN "RETURN 1" {} {"mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}

C: RUN "RETURN 1" {} {"mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}