!: BOLT 4
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9001

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": {"name": "molly", "age": "1"}} {}
   PULL {"n": -1}
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [302, [{"role":"ROUTE", "addresses":["127.0.0.1:9001", "127.0.0.1:9002"]}, {"role":"READ", "addresses":["127.0.0.1:9002"]}, {"role":"WRITE", "addresses":["127.0.0.1:9001"]}]]
   SUCCESS {}
