!: BOLT 4
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET
!: PORT 9004

C: BEGIN {"bookmarks": ["bookmark:1"], "mode": "r"}
S: SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "bookmark:2"}

C: RUN "RETURN 1" {} {"bookmarks": ["bookmark:2"], "mode": "r"}
   PULL {"n": -1}
S: SUCCESS {"bookmark": "bookmark:3"}
   SUCCESS {}

C: BEGIN {"bookmarks": ["bookmark:3"], "mode": "r"}
S: SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "bookmark:4"}
